name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    path:
      - 'html/**'
  pull_request:
    branches: [ "main" ]
    path:
      - 'html/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        cd html
        docker build . --file Dockerfile --tag ghcr.io/feketemiklosbenjamin/html-feketemiklos:0.2
        docker login ghcr.io -u feketemiklosbenjamin -p ${{secrets.GHCR_TOKEN}}
        docker push ghcr.io/feketemiklosbenjamin/html-feketemiklos:0.2
